posId: '300746'
posDesc: 'Point of sales description'
posCurrency: 'PLN'
clientId: '300746'
clientSecret: '2ee86a66e5d97e3fadc400c9f19b065d'
signatureKey: 'b6ca15b0d1020e8094d9b5f8d163db54'
environment: 'sandbox'
notifyUrl: 'http://shop.com/notify'
continueUrl: 'http://shop.com'
