posId: '145227'
posDesc: 'Point of sales description'
posCurrency: 'USD'
clientId: '145227'
clientSecret: '12f071174cb7eb79d4aac5bc2f07563f'
signatureKey: '13a980d4f851f3d9a1cfc792fb1f5e50'
environment: 'sandbox'
notifyUrl: 'http://shop.com/notify'
continueUrl: 'http://shop.com'
